# Generated by Django 2.1.8 on 2019-10-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title_en', models.TextField(blank=True, null=True)),
                ('about_title_ar', models.TextField(blank=True, null=True)),
                ('about_short_desc_en', models.TextField(blank=True, null=True)),
                ('about_short_desc_ar', models.TextField(blank=True, null=True)),
                ('about_long_desc_en', models.TextField(blank=True, null=True)),
                ('about_long_desc_ar', models.TextField(blank=True, null=True)),
                ('image_name', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('reservation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('time_table_en', models.TextField(blank=True, null=True)),
                ('time_table_ar', models.TextField(blank=True, null=True)),
                ('Facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('Instgram', models.CharField(blank=True, max_length=255, null=True)),
                ('Youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('GoogleBussiness', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_en', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords_en', models.TextField(blank=True, null=True)),
                ('keywords_ar', models.TextField(blank=True, null=True)),
                ('logo_name', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('icon_name', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('person_name_ar', models.CharField(blank=True, max_length=150, null=True)),
                ('person_job_en', models.CharField(blank=True, max_length=255, null=True)),
                ('person_job_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('person_short_desc_en', models.TextField(blank=True, null=True)),
                ('person_short_desc_ar', models.TextField(blank=True, null=True)),
                ('person_long_desc_en', models.TextField(blank=True, null=True)),
                ('person_long_desc_ar', models.TextField(blank=True, null=True)),
                ('person_keywords_en', models.TextField(blank=True, null=True)),
                ('person_keywords_ar', models.TextField(blank=True, null=True)),
                ('person_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('person_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('person_birth_date', models.DateField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('cv_en', models.TextField(blank=True, null=True)),
                ('cv_ar', models.TextField(blank=True, null=True)),
                ('image_name', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=150, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='photo/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(blank=True, max_length=6, null=True)),
                ('service_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('service_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('short_desc_en', models.TextField(blank=True, null=True)),
                ('short_desc_ar', models.TextField(blank=True, null=True)),
                ('keywords_en', models.TextField(blank=True, null=True)),
                ('keywords_ar', models.TextField(blank=True, null=True)),
                ('long_desc_en', models.TextField(blank=True, null=True)),
                ('long_desc_ar', models.TextField(blank=True, null=True)),
                ('image_name', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('orders', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('desc_ar', models.TextField(blank=True, null=True)),
                ('image_name', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('orders', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=150, null=True)),
                ('image_name', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
